
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package jl2755;

import jl2755.ast.*;
import java.io.IOException;

/** CUP v0.11b 20150326 generated parser.
  */
public class ixiParser
 extends java_cup.runtime.lr_parser {

  @Override
  public final Class<?> getSymbolContainer() {
    return sym.class;
  }

  /** Default constructor. */
  @Deprecated
  public ixiParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ixiParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner and a SymbolFactory. */
  public ixiParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\024\000\002\002\004\000\002\007\004\000\002\007" +
    "\005\000\002\011\004\000\002\020\005\000\002\020\007" +
    "\000\002\021\003\000\002\024\003\000\002\025\006\000" +
    "\002\025\007\000\002\026\004\000\002\026\003\000\002" +
    "\033\003\000\002\033\003\000\002\037\004\000\002\037" +
    "\002\000\002\044\003\000\002\044\003\000\002\045\003" +
    "\000\002\045\005" });

  /** Access to production table. */
  @Override
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\004\004\005\001\002\000\004\044\013\001" +
    "\002\000\006\044\ufffb\050\ufffb\001\002\000\004\002\012" +
    "\001\002\000\004\002\ufffa\001\002\000\006\002\ufff6\004" +
    "\005\001\002\000\004\002\ufff7\001\002\000\004\002\001" +
    "\001\002\000\006\004\005\045\016\001\002\000\004\050" +
    "\037\001\002\000\004\045\035\001\002\000\010\002\ufff2" +
    "\004\ufff2\050\020\001\002\000\006\002\ufff9\004\ufff9\001" +
    "\002\000\006\024\026\025\023\001\002\000\012\002\ufff0" +
    "\004\ufff0\045\ufff0\051\ufff0\001\002\000\006\002\ufff3\004" +
    "\ufff3\001\002\000\014\002\ufff4\004\ufff4\042\ufff4\045\ufff4" +
    "\051\ufff4\001\002\000\014\002\ufff1\004\ufff1\042\031\045" +
    "\ufff1\051\ufff1\001\002\000\010\002\uffef\004\uffef\051\027" +
    "\001\002\000\014\002\ufff5\004\ufff5\042\ufff5\045\ufff5\051" +
    "\ufff5\001\002\000\006\024\026\025\023\001\002\000\006" +
    "\002\uffee\004\uffee\001\002\000\004\043\033\001\002\000" +
    "\012\002\ufffe\004\ufffe\045\ufffe\051\ufffe\001\002\000\014" +
    "\002\000\004\000\042\031\045\000\051\000\001\002\000" +
    "\012\002\uffff\004\uffff\045\uffff\051\uffff\001\002\000\010" +
    "\002\ufff2\004\ufff2\050\020\001\002\000\006\002\ufff8\004" +
    "\ufff8\001\002\000\006\024\026\025\023\001\002\000\006" +
    "\045\ufffd\051\041\001\002\000\004\004\005\001\002\000" +
    "\004\045\ufffc\001\002" });

  /** Access to parse-action table. */
  @Override
  public short[][] action_table() {return _action_table;}

  /** {@code reduce_goto} table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\012\021\003\024\005\025\007\026\006\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\021\003\025\007\026\010\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\020\014" +
    "\021\013\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\037\016\001\001\000\002\001\001\000\012\011\020" +
    "\033\023\044\024\045\021\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\031\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\011\020\033" +
    "\023\044\024\045\027\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\007\033\001\001\000" +
    "\002\001\001\000\004\037\035\001\001\000\002\001\001" +
    "\000\010\011\020\033\023\044\037\001\001\000\002\001" +
    "\001\000\006\020\041\021\013\001\001\000\002\001\001" +
    "" });

  /** Access to {@code reduce_goto} table. */
  @Override
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ixiParser$actions action_obj;

  /** Action encapsulation object initializer. */
  @Override
  protected void init_actions()
    {
      action_obj = new CUP$ixiParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack<java_cup.runtime.Symbol> stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ixiParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  @Override
  public int start_state() {return 0;}
  /** Indicates start production. */
  @Override
  public int start_production() {return 0;}

  /** {@code EOF} Symbol index. */
  @Override
  public int EOF_sym() {return 0;}

  /** {@code error} Symbol index. */
  @Override
  public int error_sym() {return 1;}


 
  public void report_fatal_error(String msg, Object info) {
    report_error(msg, info);
  }

  public void report_error(String msg, Object info) {
    Main.setToken((java_cup.runtime.Symbol)info);
    Main.handleSyntaxError("Syntax error: unexpected ");
  }


/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ixiParser$actions {
    private final ixiParser parser;

    /** Constructor */
    CUP$ixiParser$actions(ixiParser parser) {
        this.parser = parser;
    }

    /** Method with the actual generated action code for actions 0 to 19. */
    public final java_cup.runtime.Symbol CUP$ixiParser$do_action_part00000000(
            int                        CUP$ixiParser$act_num,
            java_cup.runtime.lr_parser CUP$ixiParser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$ixiParser$stack,
            int                        CUP$ixiParser$top)
            throws java.lang.Exception {
            /* Symbol object for return from actions */
            java_cup.runtime.Symbol CUP$ixiParser$result;

        /* select the action based on the action number */
        switch (CUP$ixiParser$act_num) {
        /*. . . . . . . . . . . . . . . . . . . .*/
        case 0: // $START ::= interface EOF 
            {
                Object RESULT = null;
                int start_valleft = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1).left;
                int start_valright = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1).right;
                Interface start_val = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1).<Interface> value();
                RESULT = start_val;
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("$START",0, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1), CUP$ixiParser$stack.peek(), RESULT);
            }
            /* ACCEPT */
            CUP$ixiParser$parser.done_parsing();
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 1: // brackets ::= OPEN_BRACKET CLOSE_BRACKET 
            {
                Brackets RESULT = null;
                 RESULT = new Brackets(); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("brackets",5, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 2: // brackets ::= OPEN_BRACKET CLOSE_BRACKET brackets 
            {
                Brackets RESULT = null;
                int bleft = CUP$ixiParser$stack.peek().left;
                int bright = CUP$ixiParser$stack.peek().right;
                Brackets b = CUP$ixiParser$stack.peek().<Brackets> value();
                 RESULT = new Brackets(b); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("brackets",5, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 3: // empty_array_type ::= primitive_type brackets 
            {
                EmptyArrayType RESULT = null;
                int ptleft = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1).left;
                int ptright = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1).right;
                PrimitiveType pt = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1).<PrimitiveType> value();
                int bleft = CUP$ixiParser$stack.peek().left;
                int bright = CUP$ixiParser$stack.peek().right;
                Brackets b = CUP$ixiParser$stack.peek().<Brackets> value();
                 RESULT = new EmptyArrayType(pt, b); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("empty_array_type",7, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 4: // function_param ::= identifier COLON type 
            {
                FunctionParam RESULT = null;
                int idleft = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).left;
                int idright = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).right;
                Identifier id = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).<Identifier> value();
                int tleft = CUP$ixiParser$stack.peek().left;
                int tright = CUP$ixiParser$stack.peek().right;
                Type t = CUP$ixiParser$stack.peek().<Type> value();
                 RESULT = new FunctionParam(id, t); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("function_param",14, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 5: // function_param ::= identifier COLON type COMMA function_param 
            {
                FunctionParam RESULT = null;
                int idleft = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-4).left;
                int idright = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-4).right;
                Identifier id = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-4).<Identifier> value();
                int tleft = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).left;
                int tright = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).right;
                Type t = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).<Type> value();
                int fpleft = CUP$ixiParser$stack.peek().left;
                int fpright = CUP$ixiParser$stack.peek().right;
                FunctionParam fp = CUP$ixiParser$stack.peek().<FunctionParam> value();
                 RESULT = new FunctionParam(id, t, fp); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("function_param",14, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-4), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 6: // identifier ::= IDENTIFIER 
            {
                Identifier RESULT = null;
                int idleft = CUP$ixiParser$stack.peek().left;
                int idright = CUP$ixiParser$stack.peek().right;
                String id = CUP$ixiParser$stack.peek().<String> value();
                 RESULT = new Identifier(id, idleft, idright); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("identifier",15, CUP$ixiParser$stack.peek(), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 7: // interface ::= interface_list 
            {
                Interface RESULT = null;
                int illeft = CUP$ixiParser$stack.peek().left;
                int ilright = CUP$ixiParser$stack.peek().right;
                InterfaceList il = CUP$ixiParser$stack.peek().<InterfaceList> value();
                 RESULT = new Interface(il); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("interface",18, CUP$ixiParser$stack.peek(), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 8: // interface_func ::= identifier OPEN_PAREN CLOSE_PAREN return_type 
            {
                InterfaceFunc RESULT = null;
                int idleft = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-3).left;
                int idright = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-3).right;
                Identifier id = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-3).<Identifier> value();
                int rtleft = CUP$ixiParser$stack.peek().left;
                int rtright = CUP$ixiParser$stack.peek().right;
                ReturnType rt = CUP$ixiParser$stack.peek().<ReturnType> value();
                 RESULT = new InterfaceFunc(id, rt); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("interface_func",19, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-3), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 9: // interface_func ::= identifier OPEN_PAREN function_param CLOSE_PAREN return_type 
            {
                InterfaceFunc RESULT = null;
                int idleft = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-4).left;
                int idright = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-4).right;
                Identifier id = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-4).<Identifier> value();
                int fpleft = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).left;
                int fpright = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).right;
                FunctionParam fp = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).<FunctionParam> value();
                int rtleft = CUP$ixiParser$stack.peek().left;
                int rtright = CUP$ixiParser$stack.peek().right;
                ReturnType rt = CUP$ixiParser$stack.peek().<ReturnType> value();
                 RESULT = new InterfaceFunc(id, fp, rt); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("interface_func",19, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-4), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 10: // interface_list ::= interface_func interface_list 
            {
                InterfaceList RESULT = null;
                int ifdleft = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1).left;
                int ifdright = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1).right;
                InterfaceFunc ifd = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1).<InterfaceFunc> value();
                int illeft = CUP$ixiParser$stack.peek().left;
                int ilright = CUP$ixiParser$stack.peek().right;
                InterfaceList il = CUP$ixiParser$stack.peek().<InterfaceList> value();
                 RESULT = new InterfaceList(ifd, il); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("interface_list",20, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 11: // interface_list ::= interface_func 
            {
                InterfaceList RESULT = null;
                int ifdleft = CUP$ixiParser$stack.peek().left;
                int ifdright = CUP$ixiParser$stack.peek().right;
                InterfaceFunc ifd = CUP$ixiParser$stack.peek().<InterfaceFunc> value();
                 RESULT = new InterfaceList(ifd); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("interface_list",20, CUP$ixiParser$stack.peek(), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 12: // primitive_type ::= INT 
            {
                PrimitiveType RESULT = null;
                int ileft = CUP$ixiParser$stack.peek().left;
                int iright = CUP$ixiParser$stack.peek().right;
                Object i = CUP$ixiParser$stack.peek().<Object> value();
                 RESULT = new PrimitiveType(0); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("primitive_type",25, CUP$ixiParser$stack.peek(), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 13: // primitive_type ::= BOOL 
            {
                PrimitiveType RESULT = null;
                int bleft = CUP$ixiParser$stack.peek().left;
                int bright = CUP$ixiParser$stack.peek().right;
                Object b = CUP$ixiParser$stack.peek().<Object> value();
                 RESULT = new PrimitiveType(1); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("primitive_type",25, CUP$ixiParser$stack.peek(), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 14: // return_type ::= COLON type_list 
            {
                ReturnType RESULT = null;
                int tlleft = CUP$ixiParser$stack.peek().left;
                int tlright = CUP$ixiParser$stack.peek().right;
                TypeList tl = CUP$ixiParser$stack.peek().<TypeList> value();
                 RESULT = new ReturnType(tl); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("return_type",29, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-1), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 15: // return_type ::= 
            {
                ReturnType RESULT = null;
                 RESULT = new ReturnType(); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("return_type",29, CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 16: // type ::= primitive_type 
            {
                Type RESULT = null;
                int ptleft = CUP$ixiParser$stack.peek().left;
                int ptright = CUP$ixiParser$stack.peek().right;
                PrimitiveType pt = CUP$ixiParser$stack.peek().<PrimitiveType> value();
                 RESULT = pt; 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("type",34, CUP$ixiParser$stack.peek(), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 17: // type ::= empty_array_type 
            {
                Type RESULT = null;
                int atleft = CUP$ixiParser$stack.peek().left;
                int atright = CUP$ixiParser$stack.peek().right;
                EmptyArrayType at = CUP$ixiParser$stack.peek().<EmptyArrayType> value();
                 RESULT = at; 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("type",34, CUP$ixiParser$stack.peek(), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 18: // type_list ::= type 
            {
                TypeList RESULT = null;
                int tleft = CUP$ixiParser$stack.peek().left;
                int tright = CUP$ixiParser$stack.peek().right;
                Type t = CUP$ixiParser$stack.peek().<Type> value();
                 RESULT = new TypeList(t); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("type_list",35, CUP$ixiParser$stack.peek(), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 19: // type_list ::= type COMMA type_list 
            {
                TypeList RESULT = null;
                int tleft = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).left;
                int tright = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).right;
                Type t = CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2).<Type> value();
                int tlleft = CUP$ixiParser$stack.peek().left;
                int tlright = CUP$ixiParser$stack.peek().right;
                TypeList tl = CUP$ixiParser$stack.peek().<TypeList> value();
                 RESULT = new TypeList(t, tl); 
                CUP$ixiParser$result = parser.getSymbolFactory().newSymbol("type_list",35, CUP$ixiParser$stack.elementAt(CUP$ixiParser$top-2), CUP$ixiParser$stack.peek(), RESULT);
            }
            return CUP$ixiParser$result;

        /* . . . . . .*/
        default:
            throw new Exception(
                  "Invalid action number " + CUP$ixiParser$act_num + " found in internal parse table");

        }
    } /* end of method */

    /** Method splitting the generated action code into several parts. */
    public final java_cup.runtime.Symbol CUP$ixiParser$do_action(
            int                        CUP$ixiParser$act_num,
            java_cup.runtime.lr_parser CUP$ixiParser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$ixiParser$stack,
            int                        CUP$ixiParser$top)
            throws java.lang.Exception {
            return CUP$ixiParser$do_action_part00000000(
                           CUP$ixiParser$act_num,
                           CUP$ixiParser$parser,
                           CUP$ixiParser$stack,
                           CUP$ixiParser$top);
    }
}

}
